from __future__ import annotations

import json
import math
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Protocol
from urllib.parse import urlparse


DEFAULT_OUTPUT_ROOT = Path("sources")


class Doc2mdError(RuntimeError):
    pass


class ProviderError(Doc2mdError):
    def __init__(self, message: str, *, status_code: int, code: str = "") -> None:
        super().__init__(message)
        self.status_code = status_code
        self.code = code


@dataclass(frozen=True)
class Asset:
    relative_path: Path
    content: bytes


@dataclass(frozen=True)
class Document:
    source: str
    source_id: str
    title: str
    body: str
    updated_at: str
    source_url: str = ""
    created_at: str = ""
    path_parts: tuple[str, ...] = field(default_factory=tuple)
    metadata: dict[str, Any] = field(default_factory=dict)
    assets: tuple[Asset, ...] = field(default_factory=tuple)

    @property
    def revision(self) -> str:
        return self.updated_at

    def relative_path(self, output_root: Path = DEFAULT_OUTPUT_ROOT) -> Path:
        parts = [*output_root.parts, self.source]
        parts.extend(slugify(part) for part in self.path_parts if part)
        filename = f"{slugify(self.title)}--{short_id(self.source_id)}.md"
        return Path(*parts, filename)

    def render(self, *, ingested_at: str | None = None) -> str:
        values: dict[str, Any] = {
            "generated": True,
            "source": self.source,
            "source_id": self.source_id,
            "source_url": self.source_url,
            "title": self.title,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "ingested_at": ingested_at or now_iso(),
        }
        values.update(self.metadata)
        frontmatter = ["---"]
        for key, value in values.items():
            if value in (None, "", [], {}):
                continue
            frontmatter.append(f"{key}: {json.dumps(value, ensure_ascii=False, sort_keys=True)}")
        frontmatter.extend(
            [
                "---",
                "",
                "<!-- Generated by doc2md. Edit the source document, not this file. -->",
                "",
            ]
        )
        return "\n".join(frontmatter) + self.body.rstrip() + "\n"


class Provider(Protocol):
    def documents(self) -> list[Document]: ...


class Repository:
    def __init__(self, path: Path, *, output_root: Path = DEFAULT_OUTPUT_ROOT):
        self.path = path
        self.output_root = _validate_output_root(output_root)
        self.manifest_path = self.output_root / ".doc2md" / "manifest.json"
        self.manifest = self._load_manifest()

    def known_revisions(self, source: str) -> dict[str, str]:
        entries = self.manifest.get("sources", {}).get(source, {})
        return {source_id: entry.get("revision", "") for source_id, entry in entries.items()}

    def apply(
        self,
        source: str,
        documents: Iterable[Document],
        *,
        complete: bool = True,
        allow_bulk_delete: bool = False,
    ) -> dict[str, int]:
        previous = self.manifest.setdefault("sources", {}).setdefault(source, {})
        current: dict[str, dict[str, Any]] = {}
        counts = {"created": 0, "updated": 0, "unchanged": 0, "deleted": 0}
        sync_time = now_iso()

        for document in documents:
            if document.source != source:
                raise Doc2mdError(
                    f"document {document.source_id} belongs to {document.source}, not {source}"
                )
            relative = document.relative_path(self.output_root)
            self._validate_generated_path(relative)
            target = self.path / relative
            old_entry = previous.get(document.source_id)
            old_relative = Path(old_entry["path"]) if old_entry and old_entry.get("path") else None
            ingested_at = (
                old_entry.get("ingested_at", sync_time)
                if old_entry and old_entry.get("revision") == document.revision
                else sync_time
            )
            rendered = document.render(ingested_at=ingested_at)

            if old_relative and old_relative != relative:
                self._remove(old_relative)

            asset_paths: list[str] = []
            for asset in document.assets:
                self._validate_generated_path(asset.relative_path)
                asset_target = self.path / asset.relative_path
                asset_target.parent.mkdir(parents=True, exist_ok=True)
                if not asset_target.exists() or asset_target.read_bytes() != asset.content:
                    asset_target.write_bytes(asset.content)
                asset_paths.append(asset.relative_path.as_posix())

            old_asset_paths = set(old_entry.get("assets", [])) if old_entry else set()
            for stale_path in old_asset_paths - set(asset_paths):
                self._remove(Path(stale_path))

            before = target.read_text() if target.exists() else None
            if before == rendered:
                counts["unchanged"] += 1
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(rendered)
                counts["created" if before is None else "updated"] += 1

            current[document.source_id] = {
                "path": relative.as_posix(),
                "revision": document.revision,
                "updated_at": document.updated_at,
                "ingested_at": ingested_at,
                "assets": sorted(asset_paths),
            }

        if not complete:
            for source_id, entry in previous.items():
                current.setdefault(source_id, entry)
        else:
            removed = sorted(set(previous) - set(current))
            if _is_bulk_delete(len(previous), len(removed)) and not allow_bulk_delete:
                raise Doc2mdError(
                    f"refusing to delete {len(removed)} of {len(previous)} {source} documents; "
                    "rerun with --allow-bulk-delete after checking provider access"
                )
            for source_id in removed:
                entry = previous[source_id]
                for relative in [entry.get("path"), *entry.get("assets", [])]:
                    if relative:
                        self._remove(Path(relative))
                counts["deleted"] += 1

        self.manifest["version"] = 1
        self.manifest["updated_at"] = sync_time
        self.manifest["sources"][source] = current
        self._write_manifest()
        return counts

    def _load_manifest(self) -> dict[str, Any]:
        path = self.path / self.manifest_path
        if not path.exists():
            return {"version": 1, "sources": {}}
        data = json.loads(path.read_text())
        if data.get("version") != 1 or not isinstance(data.get("sources"), dict):
            raise Doc2mdError(f"unsupported manifest at {path}")
        return data

    def _write_manifest(self) -> None:
        path = self.path / self.manifest_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.manifest, indent=2, sort_keys=True) + "\n")

    def _remove(self, relative: Path) -> None:
        self._validate_generated_path(relative)
        target = self.path / relative
        if target.exists():
            target.unlink()

    def _validate_generated_path(self, path: Path) -> None:
        pure = PurePosixPath(path.as_posix())
        root = PurePosixPath(self.output_root.as_posix())
        if (
            pure.is_absolute()
            or ".." in pure.parts
            or len(pure.parts) <= len(root.parts)
            or pure.parts[: len(root.parts)] != root.parts
        ):
            raise Doc2mdError(f"unsafe generated path: {path}")


class GitCheckout:
    def __init__(
        self,
        remote: str,
        branch: str = "main",
        *,
        auth_header: str = "",
        author_name: str = "doc2md",
        author_email: str = "doc2md@localhost",
        output_root: Path = DEFAULT_OUTPUT_ROOT,
    ) -> None:
        self.remote = remote
        self.branch = branch
        self.auth_header = auth_header
        self.author_name = author_name
        self.author_email = author_email
        self.output_root = _validate_output_root(output_root)
        self._http_scope = _http_scope(remote, auth_header)
        self._tmp: tempfile.TemporaryDirectory[str] | None = None
        self.path: Path | None = None

    def __enter__(self) -> Path:
        self._tmp = tempfile.TemporaryDirectory(prefix="doc2md-")
        self.path = Path(self._tmp.name) / "repo"
        try:
            self._git(
                "clone",
                "--branch",
                self.branch,
                "--single-branch",
                self.remote,
                str(self.path),
                cwd=Path(self._tmp.name),
            )
            self._git("config", "user.name", self.author_name)
            self._git("config", "user.email", self.author_email)
            self._git("config", "commit.gpgsign", "false")
        except subprocess.CalledProcessError as exc:
            self._tmp.cleanup()
            self._tmp = None
            self.path = None
            raise Doc2mdError("Git clone or checkout configuration failed") from exc
        return self.path

    def commit_and_push(self, message: str) -> bool:
        assert self.path is not None
        try:
            if not self._git("status", "--porcelain", capture=True).strip():
                return False
            self._git("add", "--", self.output_root.as_posix())
            self._git("commit", "-m", message)
        except subprocess.CalledProcessError as exc:
            raise Doc2mdError("Git commit failed") from exc
        for attempt in range(1, 4):
            try:
                self._git("fetch", "origin", self.branch)
                self._git("rebase", f"origin/{self.branch}")
                self._git("push", "origin", f"HEAD:{self.branch}")
                return True
            except subprocess.CalledProcessError:
                self._git("rebase", "--abort", check=False)
                if attempt == 3:
                    raise Doc2mdError("Git push failed after three fetch/rebase attempts")
        return False

    def __exit__(self, *_args: object) -> None:
        if self._tmp:
            self._tmp.cleanup()

    def _git(
        self,
        *args: str,
        cwd: Path | None = None,
        capture: bool = False,
        check: bool = True,
    ) -> str:
        environment = os.environ.copy()
        if self.auth_header:
            environment.update(
                {
                    "GIT_CONFIG_COUNT": "1",
                    "GIT_CONFIG_KEY_0": f"http.{self._http_scope}.extraHeader",
                    "GIT_CONFIG_VALUE_0": self.auth_header,
                }
            )
        result = subprocess.run(
            ["git", *args],
            cwd=cwd or self.path,
            check=check,
            env=environment,
            text=True,
            stdout=subprocess.PIPE if capture else None,
        )
        return result.stdout or ""


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^\w\-]+", "-", value, flags=re.UNICODE)
    value = re.sub(r"-+", "-", value).strip("-_")
    return value[:80] or "untitled"


def short_id(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9]", "", value)
    return (normalized or "unknown")[-12:]


def now_iso() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _validate_output_root(path: Path) -> Path:
    pure = PurePosixPath(path.as_posix())
    if pure.is_absolute() or ".." in pure.parts or not pure.parts or pure == PurePosixPath("."):
        raise Doc2mdError(f"unsafe output root: {path}")
    return Path(*pure.parts)


def _http_scope(remote: str, auth_header: str) -> str:
    if not auth_header:
        return ""
    parsed = urlparse(remote)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise Doc2mdError("git.auth_header requires an HTTP or HTTPS remote")
    return f"{parsed.scheme}://{parsed.netloc}/"


def _is_bulk_delete(existing: int, removed: int) -> bool:
    if removed == 0:
        return False
    return removed == existing or removed > 10 or (existing >= 4 and removed > math.ceil(existing * 0.25))
